# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*
- release/3.0.0

pool:
  vmImage: 'macos-latest'

variables:
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_FULL.zip'
  RepoName: AgoraIO

jobs:

- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'FaceUnityWindows'
    workingDirectory: 'Agora-Video-With-FaceUnity-Windows'
    scheme: 'Agora-Video-With-FaceUnity-Windows'
    sdkVersion: '3_0_0'
    sdkFolderVersion: '3.0.0'
    faceUnitySDKVersion: '6.6.0'
    Machine: x86
    solutionName: 'AgoraFaceUnityTutorial.sln'
