# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''  
  sdkVersion: ''
  sdkFolderVersion: ''
  faceUnitySDKVersion: ''
  Machine: ''
  solutionName: ''
jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'vs2017-win2016'

    variables:
      solution: '${{ parameters.workingDirectory }}/${{ parameters.solutionName }}'
      buildPlatform: 'win32'
      buildConfiguration: 'Release'
      WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(${{ parameters.Machine }})_v${{ parameters.Machine }}_FULL.zip'
	  FaceUnitySDK: 'https://github.com/AgoraIO/FaceUnityLegacy/releases/download/${{ parameters.Machine }}/FaceUnitySDK-Windows.zip'
	  Windows-Dependencies: 'https://github.com/AgoraIO/FaceUnityLegacy/releases/download/6.6.0/windows-depencies.zip'
	  sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v${{ parameters.sdkFolderVersion }}_FULL'
    steps:
      - script: echo "${{ parameters.sdkurl }}" && ls
	  #AgoraSDK
	  - powershell: cicd/script/downloadsdk.ps1 "$(WindowsRTCSDK)" "AgoraSDK.zip"
	  #faceUnitySDK
      - powershell: cicd/script/downloadsdk.ps1 "$(FaceUnitySDK)" "FaceUnity.zip"
	  #dependencies
	  - powershell: cicd/script/downloadsdk.ps1 "$(Windows-Dependencies)" "windows-dependencies.zip"
	 
	  - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'AgoraSDK.zip' 
          destinationFolder: 'AgoraSDK'    

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'FaceUnity.zip' 
          destinationFolder: 'FaceUnity'    
	  - script: ls
	  - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'windows-dependencies.zip' 
          destinationFolder: 'windows-dependencies'    
      - script: ls
          
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(sdkunzipPath)/sdk
          targetFolder: ${{ parameters.workingDirectory }}/sdk

      - task: CopyFiles@2
        inputs:
          sourceFolder: 'windows-dependencies/openssl/openssl'
          targetFolder: ${{ parameters.workingDirectory }}/openssl
      - script: ls
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'windows-dependencies/ThirdParty'
          targetFolder: ${{ parameters.workingDirectory }}/ThirdParty
      - script: ls
      - script: cd ${{ parameters.workingDirectory }} && ls
      - script: ls       
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          vsVersion: '15.0'
          msbuildArchitecture: 'x86'
   
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '${{ parameters.workingDirectory }}/Release/'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          ArtifactName: ${{ parameters.displayName }}


      
